version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: climbing-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: climbing
      MYSQL_USER: climbing
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql-data: