spring:
  application:
    name: climbing-calendar
  profiles:
    active: local-h2
    group:
      local-h2:
        - local-h2-datasource
        - local-jwt
        - local-frontend
      local-mysql:
        - local-mysql-datasource
        - local-jwt
        - local-frontend
    include:
      - oauth
      - datasource
      - jwt
---
sprinG:
  config:
    activate:
      on-profile: local-frontend
frontend-url: http://localhost:3000
